version: "3"

services:
    spigot:
        build:
            context: ./spigot
            args:
                - MINECRAFT_VERSION=1.17.1
        networks:
            - default
        volumes:
            - ./world:/spigot/world
            - ./world_nether:/spigot/world_nether
            - ./world_the_end:/spigot/world_the_end
            - ./plugins:/spigot/plugins
            - ./config/spigot.yml:/spigot/spigot.yml
            - ./config/server.properties:/spigot/server.properties
            - ./config/permissions.yml:/spigot/permissions.yml
            - ./config/ops.json:/spigot/ops.json
        expose:
            - "8123"
        ports:
            - 25565:25565
        restart: always
        tty: true
        stdin_open: true
        environment:
          TZ: Asia/Tokyo

networks:
    default:
        external:
            name: shared
