version: "3"

services:
    paper:
        build:
            context: ./papermc
        networks:
            - default
        volumes:
            - ./world:/paper/world
            - ./world_nether:/paper/world_nether
            - ./world_the_end:/paper/world_the_end
            - ./shinsekai:/paper/shinsekai
            - ./plugins:/paper/plugins
            - ./config/server.properties:/paper/server.properties
            - ./config/permissions.yml:/paper/permissions.yml
            - ./config/ops.json:/paper/ops.json
        expose:
            - "8123"
        ports:
            - 25565:25565
        restart: always
        tty: true
        stdin_open: true
        environment:
          TZ: Asia/Tokyo

networks:
    default:
        external:
            name: shared
